server:
  port: 8081

spring:
    application:
        name: USUARIO-SERVICE
    config:
        import: optional:configserver:http://localhost:8085
    datasource:
        url: jdbc:mysql://localhost:3306/microservicios
        username: root
        password: root
        driver: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    
